name: main
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 18 * * *'
env:
    "classID" : ${{ secrets.ClassID }}
    "x" : ${{ secrets.X }}
    "y" : ${{ secrets.Y }}
    "h" : ${{ secrets.H }}
    "time" : ${{ secrets.TIME }}
    "cookie" : ${{ secrets.COOKIE }}
    "settime" : ${{ secrets.SETTIME }}
    "sendkey" : ${{ secrets.SENDKEY }}
jobs:
  chekin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3
      - name: Set up env
      - run: pip install requests
             pip install beautifulsoup4
      - name: Checkin
      - run: python main.py
